SELECT * from users;

INSERT INTO users (username, email, password, nickname, profile_image, provider_type, role_type, is_email_verified)
VALUES ('김용수', 'yongsu@kakao.com', 'yongsu', '용용선생김용수', 'https://api.multiavatar.com/user-yong.svg' ,'KAKAO', 'ADMIN', 1),
    ('민준수', 'awayfromsunsu@gmail.com', 'buentae', '저수상한사람아닙니다', 'https://api.multiavatar.com/user-dasfasdf.svg' ,'GOOGLE', 'ADMIN', 1),
    ('남보우', 'nbo@naver.com', 'nbo', '반장남보보우우', 'https://api.multiavatar.com/user-fwww.svg' ,'NAVER', 'ADMIN', 1),
    ('박준엽', 'junyeop@ssafy.com', 'junjun', '레거시아저씨박준엽', 'https://api.multiavatar.com/user-legacy.svg' ,'LOCAL', 'USER', 1),
    ('김훈민', 'hunhun@gmail.com', 'hunmin', '싸피셜기자단김훈민', 'https://api.multiavatar.com/user-hun.svg' ,'GOOGLE', 'USER', 1),
    ('이인준', 'injun@naver.com', 'injun', '십자인대삽니다', 'https://api.multiavatar.com/user-sipza.svg' ,'NAVER', 'USER', 1),
    ('양준영', 'jangjang@ssafy.com', 'junjun', '아크샨노밴좀', 'https://api.multiavatar.com/user-aka.svg' ,'LOCAL', 'USER', 1),
    ('황성민', 'hwang@kakao.com', 'car', '조수석타실분', 'https://api.multiavatar.com/user-car.svg' ,'KAKAO', 'USER', 1),
    ('박진우', 'park@ssafy.com', 'jinjinzara', '아이작초고수', 'https://api.multiavatar.com/user-izac.svg' ,'LOCAL', 'USER', 1),
    ('손지석', 'sonzi@gmail.com', 'sonzi', '고점매수저점매도', 'https://api.multiavatar.com/user-bitcoin.svg' ,'GOOGLE', 'USER', 1),
    ('임경혜', 'im@naver.com', 'imim', '광주5반오너', 'https://api.multiavatar.com/user-owner.svg' ,'NAVER', 'USER', 1),
    ('손흥민', 'son@gmail.com', 'son', '월클손흥민', 'https://api.multiavatar.com/user-son.svg' ,'GOOGLE', 'USER', 1),
    ('박지수', 'jisoo@kakao.com', 'jisoo123', '지지박지수', 'https://api.multiavatar.com/user-jisoo.svg', 'KAKAO', 'USER', 1),
    ('이서준', 'seojun@naver.com', 'seojun88', '멋진서준', 'https://api.multiavatar.com/user-seojun.svg', 'NAVER', 'USER', 1),
    ('최민호', 'minho@gmail.com', 'choim', '최미노', 'https://api.multiavatar.com/user-minho.svg', 'GOOGLE', 'USER', 1),
    ('한유리', 'yuri@kakao.com', 'han123', '유리한유리', 'https://api.multiavatar.com/user-yuri.svg', 'KAKAO', 'USER', 1),
    ('정유진', 'yujin@gmail.com', 'yujin234', '유진정유', 'https://api.multiavatar.com/user-yujin.svg', 'GOOGLE', 'USER', 1),
    ('오준호', 'junho@naver.com', 'junho567', '오준호비', 'https://api.multiavatar.com/user-junho.svg', 'NAVER', 'USER', 1),
    ('윤지후', 'jihuyoon@ssafy.com', 'jihuman', '지후윤지', 'https://api.multiavatar.com/user-jihu.svg', 'LOCAL', 'USER', 1),
    ('백승현', 'baeksh@google.com', 'baekman', '승현백백', 'https://api.multiavatar.com/user-seunghyun.svg', 'GOOGLE', 'USER', 1),
    ('신혜림', 'hyerim@naver.com', 'hyerim123', '혜림신신', 'https://api.multiavatar.com/user-hyerim.svg', 'NAVER', 'USER', 1),
    ('강민지', 'minji@gmail.com', 'minji678', '민지강강', 'https://api.multiavatar.com/user-minji.svg', 'GOOGLE', 'USER', 1),
    ('김도훈', 'dohoon@kakao.com', 'dohoon123', '도훈김김', 'https://api.multiavatar.com/user-dohoon.svg', 'KAKAO', 'USER', 1),
    ('이하준', 'hajun@gmail.com', 'hajun789', '하준이이', 'https://api.multiavatar.com/user-hajun.svg', 'GOOGLE', 'USER', 1),
    ('김싸피', 'ssafy@ssafy.com', 'ssafy', '싸피오브김싸피', 'https://api.multiavatar.com/user-123123.svg' ,'GOOGLE', 'USER', 1),
    ('나싸피', 'ssafy1@ssafy.com', 'ssafy', '싸피오브나싸피', 'https://api.multiavatar.com/user-1231234.svg' ,'NAVER', 'USER', 1),
    ('박싸피', 'ssafy2@ssafy.com', 'ssafy', '싸피오브박싸피', 'https://api.multiavatar.com/user-123.svg' ,'LOCAL', 'USER', 1),
    ('이싸피', 'ssafy3@ssafy.com', 'ssafy', '싸피오브이싸피', 'https://api.multiavatar.com/user-234.svg' ,'GITHUB', 'USER', 1);